using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Orbita.Domain.Audit;
using Orbita.Domain.Identity;
using Orbita.Domain.Tenants;

namespace Orbita.Infrastructure.Persistence.Configurations;

/// <summary>
/// Standard tenant isolation (query filter here, RLS + tenant-first indexes in the
/// migration) — audit_log is a normal tenant-scoped table, unlike Subscription/
/// InvitationToken/PasswordResetToken: it's always read with a known tenant (an
/// Owner/Admin viewing their own trail), never looked up by an external opaque id
/// before a tenant is known.
/// </summary>
public sealed class AuditLogEntryConfiguration : IEntityTypeConfiguration<AuditLogEntry>
{
    public void Configure(EntityTypeBuilder<AuditLogEntry> builder)
    {
        builder.ToTable("audit_log");

        builder.HasKey(e => e.Id);
        // "id bigint [pk, increment]" in orbita-schema.dbml maps to Postgres bigserial/
        // GENERATED BY DEFAULT AS IDENTITY semantics, not GENERATED ALWAYS — matches
        // every other dbdiagram.io "increment" column being an ordinary serial.
        builder.Property(e => e.Id).HasColumnName("id").UseIdentityByDefaultColumn();

        builder.Property(e => e.TenantId).HasColumnName("tenant_id").IsRequired();
        builder.Property(e => e.ActorId).HasColumnName("actor_id");
        builder.Property(e => e.ActorType).HasColumnName("actor_type").HasConversion<string>().HasMaxLength(20).IsRequired();
        builder.Property(e => e.Action).HasColumnName("action").HasMaxLength(AuditLogEntry.ActionMaxLength).IsRequired();
        builder.Property(e => e.EntityType).HasColumnName("entity_type").HasMaxLength(AuditLogEntry.EntityTypeMaxLength).IsRequired();
        builder.Property(e => e.EntityId).HasColumnName("entity_id");
        builder.Property(e => e.DiffJson).HasColumnName("diff").HasColumnType("jsonb");
        builder.Property(e => e.IpAddress).HasColumnName("ip");
        builder.Property(e => e.UserAgent).HasColumnName("user_agent");
        builder.Property(e => e.CreatedAt).HasColumnName("created_at").IsRequired();

        builder.HasIndex(e => new { e.TenantId, e.CreatedAt });
        builder.HasIndex(e => new { e.TenantId, e.EntityType, e.EntityId });

        builder.HasOne<Tenant>().WithMany().HasForeignKey(e => e.TenantId);
        builder.HasOne<User>().WithMany().HasForeignKey(e => e.ActorId);
    }
}
